name: Check File Changes

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full commit history is fetched

    - name: Set up permissions for the script
      run: chmod +x .github/scripts/check_files.sh

    - name: Run file change check script
      run: .github/scripts/check_files.sh
